### ISSUE TITLE
Consider asyncio features ala asyncblink

### ISSUE THREAD

**Issue by jek** [jek/blinker#17]
"[AsyncBlink](https://pypi.python.org/pypi/asyncblink/) is a small extention to Blinker and enables you to use coroutines as receivers for your signals."

Seems to be essentially a modification of `send()` like so:

``` python
        # the only difference is here. If it's a coroutine,
        # run it with asyncio.async()
        receivers = self.receivers_for(sender) or []
        return_list = []

        for receiver in receivers:
            ret = receiver(sender, **kwargs)
            if asyncio.coroutines.iscoroutine(ret):
                ret = asyncio.async(ret)
            return_list.append((receiver, ret))

        return return_list
```

Useful to have this in Blinker natively?  Perhaps something ala:

``` python
def send_async(self, *sender, **kw):
    wrapped = lambda v: asyncio.coroutine(lambda: v)
    values = [(r, wrapped(v)) if asyncio.iscoroutine(v) else (r, v)
                   for r, v in self.send(*sender, **kw)]
    return asyncio.gather(*values)
```

cc: @jucacrispim

**Comment by jucacrispim** [comment]
Hi, @jek 
It would be great to have this funcionality in Blinker. I have just one thing to say about the send_async(). When you use asyncio.gather() you are waiting for all the Futures to complete, right? In my case, at least, I don't want to wait for the Futures. I'm using it in a continuous integration softwrare[1] and I do some tcp connections that are expansive. So, IMO, it would be great if we don't wait for the Futures or have a param to indicate if we should wait for it or not.

[1] https://gitlab.com/toxicbuild/toxicbuild. The 'master' branch for this project is the old stuff, based on buildbot. There is a brach called 'rewrite' and is in this branch that I'm using coroutines with signals. The 'rewrite' branch is not fully working, I'm still working on a UI and in documentation. I hope in few weeks to merge 'rewrite' with 'master'.

**Comment by jek** [comment]
@jucacrispim that makes sense. I updated the PR in #18 to not use gather- how does that look?

In either case, it seems like there should be a way to pass a loop in for the scheduling, and I'm mulling over the best way to do that. A `loop` keyword arg to send_async() would mean that signals couldn't receive a 'loop' arg (send_async would absorb it), and other options don't seem wonderful either.

**Comment by jucacrispim** [comment]
I think that the PR #18 is ok. I liked that code.

About the loop I think that using an arg to send_async() is ok. I think that makes sense to pass a different loop to send_async().

**Comment by jek** [comment]
Update: I'm increasingly +1 about this addition, and intend to land it once I get off the fence about the function signature.

**Comment by smurfix** [comment]
Any progress? it's been a year.

WRT the loop argument: Set it in the signal's constructor. There's no use case for objects that get passed around from one asyncio loop to another.

**Comment by jucacrispim** [comment]
`May I suggest another thing instead of the loop argument?
`
At first I thought that passing a loop would be useful to use different types of coroutines (ie tornado coroutines) not only asyncio ones. But these days I was changing [asyncblink](https://github.com/jucacrispim/asyncblink) and I found that for this purpose is easier to pass the scheduler function when connecting the reciever to a signal. Something like:

```python
my_signal.connect(reciever, scheduler=scheduler_function)
```
And then use scheduler_function instead of asyncio.ensure_function.

**Comment by smurfix** [comment]
Hmm. That would just force me to call my_signal.connect(receiver, scheduler=self._loop.call_soon)) everywhere, instead of setting that up once when initializing my_signal. Not my preferred solution.

On the other hand, we could have it both ways by passing a default scheduler to .__init__() and using that if none is given at connect() time. 

On the third hand, I wonder whether there's a real-world use case for the additional complexity, given that mixing two different kinds of async mechanism in one program is rarely a good idea.

**Comment by jek** [comment]
Thanks for the discussion around this. I haven't written anything substantial in asyncio, so hearing use case debates is incredibly useful.

I'm thinking of a neutral approach in which the `Signal` constructor accepts an optional receiver transforming/decorating function with the signature (`fn`, `sender`, `kwargs`). If provided, this is called instead of the raw receiver during `send()`. If this pans out, this mechanism can be used to implement all of the above use patterns, as well as the regularly requested and always rejected `send_robust` pattern.

**Comment by jucacrispim** [comment]
The idea of passing it to a constructor is much better indeed. My use-case for something like this is that I am working on [mongomotor](http://mongomotor.poraodojuca.net) and I'm not using different loops at the same time but I could use asyncio or tornado and would be good to be able to pass any kind of coroutines to the signals.

**Comment by jek** [comment]
Threw up a proof of concept at feature/receiver-adapter

The 2nd commit (f4c1037f3c361b5) has an adapter that implements the approach of #18 and accepts an alternate scheduling function if desired. There are a couple other POC adapters in that commit to look at as well.

This seems pretty flexible... any thoughts? I would be interested in providing a generic 80%-case async adapter natively within Blinker.

**Comment by marceloavan** [comment]
It could be a very good improvement, it's a shame that the project has been stopped since 2016.

**Comment by leandrorebelo** [comment]
OMG! I finally found a result of all my problems. The impl is very simple but very usefull.

**Comment by yackx** [comment]
First of all, thank you for blinker. It is a well-thought library that helps decreasing coupling on a large code base. Like everybody here, I appreciate the time and effort that went into blinker.

Because my team uses [starlette](https://www.starlette.io/), _the little ASGI framework that shines_, we were in dire need of async support in blinker. Unfortunatelly, https://github.com/jek/blinker/pull/18 has not been merged. So we relunctantly [forked](https://github.com/gomymove/blinker) blinker, patched it with the content of the PR, made small corrections and... it works fine.

Our goal is not to maintain a forked version of the library ; it would hardly be half as nice as the original. We'd rather spend the time and effort on the original project, within a community of motivated developers. But like several others here, we can't use blinker as is, although it's so close to async support. So, how can we help?

@no-lab @herdani

**Comment by marceloavan** [comment]
@yackx it would be great if your fork was pushed to some pip repository, considering that @jek is no answering. Is it an option for you?

**Comment by jek** [comment]
sorry all for my distance- variety of factors prevent me from contributing directly and I have no desire to hold up this project due to that.  I am very happy to add a maintainer to this project so that this can release and the ecosystem can benefit without ill effects from forking.

short term needs in the maintainer role would be to merge this work (and I am beyond pleased that this is coming from real production usage), and spruce up any of the packaging and release infrastructure that may have gone stale. and make a release of course!

my only philosophical requirement to pass the torch is agreement that the constantly requested "send_robust" is a footgun that should not be shipped api, though it should be possible for someone to either later that on themselves or through a separate plugin package. please feel free to contact me directly with interest and we can move it forward.

**Comment by yackx** [comment]
Contacted @jek by email. Will report here if applicable.

**Comment by yackx** [comment]
@jek has added me as a collaborator. The short-term plan is to revive and merge #18 then release a new version. I'll be joined by @no-lab in this endeavor.

We just started to have some production usage of a forked version of the PR, mixing sync and async receivers, and so far it works as expected.

**Comment by yackx** [comment]
Actually there wasn't much missing in the PR. I've just fixed an obsolete import construct, and added some documentation.

**Comment by yackx** [comment]
Merged #18 

We (@no-lab and me) have been running a backported version of this branch in production for a while, no reported issue. 

Our async usage of this PR has been limited however, and we are in a specific context (starlette) so we cannot extrapolate, but at least we did not encounter regression on the existing "plain old sync" signals.

**Comment by Skyross** [comment]
@yackx Sorry for bothering you, but it released in the newer version already? Also, I see no changes at [the official documentation](https://pythonhosted.org/blinker/), and looks like it needs to be updated too. Do you have an access to release the package and/or build documentation?

**Comment by yackx** [comment]
Hello @Skyross No it is not released, my powers end at the merge button in this repo. I have no access to PyPi or the official doc. I don't know if other items would be included in the next release, or if this alone justifies a release.
