### ISSUE TITLE
Asynchronus signal call

### ISSUE THREAD

**Issue by stephen-bunn** [jek/blinker#33]
Is something like the following possible with the current blinker framework?

```python
import time
import multiprocessing
import blinker

sig = blinker.signal('test')

@sig.connect
def callback(data):
    print(data)

with multiprocessing.Pool(2) as p:
    p.map(sig.send, [1, 2])
```

Basically, I would like for the signal to create a thread for the `callback` function.
Is there any optimal way of doing this currently?

**Comment by tbnorth** [comment]
It's multiprocessing's job to create threads, which it does when you call `Pool()`.  However you can't pickle instancemethods, like `sig.send()`, so you need a wrapper:

```python
import time
import multiprocessing
import blinker

sig = blinker.signal('test')

@sig.connect
def callback(data):
    print(data)

def send(data):
    sig.send(data)

if __name__ == '__main__':
    with multiprocessing.Pool(2) as p:
        p.map(send, [1, 2])
```
This runs as expected (in Python 3, in Python 2 you need to use `p = multiprocessing.Pool(2)`).

So I think this issue can be closed because blinker behaves normally within the context of multiprocessing.

**Comment by stephen-bunn** [comment]
Solved my issue! Thanks
